/* Chess-X Search Index — all site content */
window.CHESSEX_INDEX = [
  /* ── OPENINGS ── */
  { tag:"Opening", title:"Ruy Lopez", snippet:"One of the oldest and most respected openings. White pressures Black's e5 pawn with long-term domination of the centre.", url:"openings.html#ruy-lopez" },
  { tag:"Opening", title:"Italian Game", snippet:"Clean development and central control. Beloved by beginners and grandmasters alike for rich middlegame play.", url:"openings.html#italian-game" },
  { tag:"Opening", title:"King's Gambit", snippet:"A romantic, aggressive sacrifice of the f-pawn for rapid development and a kingside attack.", url:"openings.html#kings-gambit" },
  { tag:"Opening", title:"Queen's Gambit", snippet:"White offers a pawn to gain central control. Strategically profound, favoured by world champions for over a century.", url:"openings.html#queens-gambit" },
  { tag:"Opening", title:"London System", snippet:"Solid, reliable, and easy to learn. Ideal for players who want results without heavy memorisation.", url:"openings.html#london-system" },
  { tag:"Opening", title:"Catalan Opening", snippet:"Sophisticated blend of Queen's Gambit and Réti. White fianchettoes the king's bishop for long diagonal pressure.", url:"openings.html#catalan-opening" },
  { tag:"Opening", title:"Vienna Game", snippet:"A flexible and aggressive system — White keeps options open with Nc3 and can follow up with f4.", url:"openings.html#vienna-game" },
  { tag:"Opening", title:"Nimzo-Indian Defence", snippet:"Black pins White's knight before it can dominate the centre — one of the most theoretically rich openings.", url:"openings.html#nimzo-indian" },
  { tag:"Opening", title:"English Opening", snippet:"A hypermodern first move fighting for the centre with pieces rather than pawns. Transposes into countless systems.", url:"openings.html#english-opening" },
  { tag:"Opening", title:"Sicilian Defence", snippet:"The most popular and complex reply to 1.e4. Black fights for the initiative from move one with asymmetrical counterplay.", url:"openings.html#sicilian-defence" },
  { tag:"Opening", title:"French Defence", snippet:"Solid and strategic. Black concedes space to counterattack White's centre. The bad light-squared bishop is the trade-off.", url:"openings.html#french-defence" },
  { tag:"Opening", title:"Caro-Kann Defence", snippet:"The thinking player's alternative to the French — solid, active, and avoids the cramped light-squared bishop.", url:"openings.html#caro-kann" },
  { tag:"Opening", title:"Pirc Defence", snippet:"Black cedes the centre and attacks it from the flanks. A hypermodern approach demanding accurate counterplay.", url:"openings.html#pirc-defence" },
  { tag:"Opening", title:"Scandinavian Defence", snippet:"Immediate central tension — Black challenges e4 at once for quick piece activity.", url:"openings.html#scandinavian" },
  { tag:"Opening", title:"King's Indian Defence", snippet:"Fischer, Kasparov, Bronstein all loved the KID. Black allows White's centre then launches a ferocious kingside attack.", url:"openings.html#kings-indian" },
  { tag:"Opening", title:"Modern Defence", snippet:"Black fianchettoes and lets White build any centre — then immediately undermines it.", url:"openings.html#modern-defence" },
  { tag:"Opening", title:"Grünfeld Defence", snippet:"Black allows White to occupy the entire centre with pawns, then attacks it with every piece.", url:"openings.html#grunfeld-defence" },
  { tag:"Opening", title:"Dutch Defence", snippet:"Black fights for the e4 square from move one and seeks early kingside activity.", url:"openings.html#dutch-defence" },

  /* ── TACTICS ── */
  { tag:"Tactic", title:"The Fork", snippet:"A single piece attacks two or more enemy pieces simultaneously. The knight is the most infamous forking piece.", url:"tactics.html#the-fork" },
  { tag:"Tactic", title:"The Pin", snippet:"A piece cannot move without exposing a more valuable piece behind it. Absolute pins immobilise; relative pins are costly.", url:"tactics.html#the-pin" },
  { tag:"Tactic", title:"The Skewer", snippet:"A valuable piece is attacked and forced to move, exposing a lesser piece behind it. The reversed pin.", url:"tactics.html#the-skewer" },
  { tag:"Tactic", title:"Discovered Attack", snippet:"A piece moves to uncover an attack from behind — creating a double threat nearly impossible to meet.", url:"tactics.html#discovered-attack" },
  { tag:"Tactic", title:"Discovered Check", snippet:"A discovered attack where the revealed threat is check. The moving piece can wreak havoc anywhere.", url:"tactics.html#discovered-check" },
  { tag:"Tactic", title:"Double Check", snippet:"Both the moving piece and the piece behind it give check. The only legal response is to move the king.", url:"tactics.html#double-check" },
  { tag:"Tactic", title:"Zwischenzug", snippet:"The in-between move. Instead of responding to a threat, a player inserts a more powerful intermediate move.", url:"tactics.html#zwischenzug" },
  { tag:"Tactic", title:"Deflection", snippet:"A guarding piece is lured away by sacrifice, leaving its charge unprotected.", url:"tactics.html#deflection" },
  { tag:"Tactic", title:"Interference", snippet:"A piece is interposed between two enemy pieces to cut their communication — leaving one undefended.", url:"tactics.html#interference" },
  { tag:"Tactic", title:"Overloading", snippet:"A piece is doing too much. Attack both its duties in sequence and force it to abandon one.", url:"tactics.html#overloading" },
  { tag:"Tactic", title:"X-Ray Attack", snippet:"A long-range piece exerts influence through an enemy piece. Subtle and powerful.", url:"tactics.html#x-ray-attack" },
  { tag:"Tactic", title:"Zugzwang", snippet:"Any move the player makes worsens their position. Common in endgames — can decide games at the highest level.", url:"tactics.html#zugzwang" },
  { tag:"Tactic", title:"Greek Gift Sacrifice", snippet:"Bishop sacrifice on h7, driving the king into the open for a coordinated attack with knight and queen.", url:"tactics.html#greek-gift-sacrifice" },
  { tag:"Tactic", title:"Exchange Sacrifice", snippet:"Surrendering a rook for a minor piece to gain positional compensation — an outpost, bishop pair, or initiative.", url:"tactics.html#exchange-sacrifice" },
  { tag:"Tactic", title:"Back Rank Mate", snippet:"The king trapped on the back rank by its own pawns — rook or queen sweeps in for checkmate.", url:"tactics.html#back-rank-mate" },
  { tag:"Tactic", title:"Smothered Mate", snippet:"The king is surrounded by its own pieces and checkmated by a knight. Typically follows a corner sacrifice.", url:"tactics.html#smothered-mate" },
  { tag:"Tactic", title:"Stalemate Trick", snippet:"The defender sacrifices material to leave the king with no legal moves — saving the draw from a lost position.", url:"tactics.html#stalemate-trick" },
  { tag:"Tactic", title:"Underpromotion", snippet:"Promoting a pawn to rook, bishop, or knight instead of a queen — often a knight fork or mating net.", url:"tactics.html#underpromotion" },
  { tag:"Tactic", title:"Triangulation", snippet:"King moves in a triangle to lose a tempo, transferring the obligation to move to the opponent.", url:"tactics.html#triangulation" },
  { tag:"Tactic", title:"Fortress Construction", snippet:"The weaker side builds an impregnable defensive formation that cannot be broken even with massive material advantage.", url:"tactics.html#fortress-construction" },

  /* ── ENDGAMES ── */
  { tag:"Endgame", title:"The Opposition", snippet:"Two kings face each other with one square between them. The player who does not have to move holds the opposition.", url:"endgames.html#the-opposition" },
  { tag:"Endgame", title:"The Square Rule", snippet:"Can the defending king catch a passed pawn? The square rule tells you instantly.", url:"endgames.html#the-square-rule" },
  { tag:"Endgame", title:"Key Squares", snippet:"Each pawn has key squares — the squares the king must reach to guarantee promotion.", url:"endgames.html#key-squares" },
  { tag:"Endgame", title:"Trebuchet", snippet:"Mutual zugzwang where both sides have an equal pawn. Whichever king is forced to move loses.", url:"endgames.html#trebuchet" },
  { tag:"Endgame", title:"Outside Passed Pawn", snippet:"A flank passed pawn acts as a decoy, drawing the enemy king away while yours invades on the other side.", url:"endgames.html#outside-passed-pawn" },
  { tag:"Endgame", title:"Lucena Position", snippet:"The most important winning technique in rook endgames. Bridge-building escorts the pawn to promotion.", url:"endgames.html#lucena-position" },
  { tag:"Endgame", title:"Philidor Position", snippet:"The essential drawing technique. The rook cuts the king off on the sixth rank, switches to back-rank checks.", url:"endgames.html#philidor-position" },
  { tag:"Endgame", title:"Saavedra Position", snippet:"A miraculous study — White weaves zugzwang and underpromotion to secure an unlikely victory.", url:"endgames.html#saavedra-position" },
  { tag:"Endgame", title:"Queen vs Rook", snippet:"Theoretically won but practically very difficult — the defending rook gives constant checks and stalemate traps.", url:"endgames.html#queen-vs-rook" },
  { tag:"Endgame", title:"Opposite-Coloured Bishops", snippet:"Notorious drawing tendencies — material advantages melt away when bishops control different-coloured squares.", url:"endgames.html#opposite-coloured-bishops" },
  { tag:"Endgame", title:"Bishop vs Knight", snippet:"Open positions favour the bishop; closed ones favour the knight. Know which endgame to steer toward.", url:"endgames.html#bishop-vs-knight" },
  { tag:"Endgame", title:"Corresponding Squares", snippet:"A deep concept in king and pawn endgames — hidden geometry determines who can access key squares first.", url:"endgames.html#corresponding-squares" },

  /* ── BLOG ── */
  { tag:"Blog", title:"What the Opening Tells You About the Endgame", snippet:"The choices made in the first ten moves cast long shadows over the final phase of the game.", url:"blog.html#opening-endgame" },
  { tag:"Blog", title:"Fischer vs Spassky: Reykjavik 1972", snippet:"More than a chess match — a Cold War drama played over 64 squares. Game 6 may be the greatest ever played.", url:"blog.html#fischer-spassky" },
  { tag:"Blog", title:"Carlsen Crushes Gukesh in Queen Endgame", snippet:"Norway Chess 2025 — Carlsen's patient king march and model technique in 58 moves.", url:"blog.html#carlsen-gukesh" },
  { tag:"Blog", title:"Firouzja's Sacrifice Stuns Nepomniachtchi", snippet:"Candidates 2025 — a Najdorf exchange sacrifice that belongs in the anthologies.", url:"blog.html#firouzja-nepo" },
  { tag:"Blog", title:"Prophylaxis: The Art of Preventing What Has Not Yet Happened", snippet:"Petrosian's genius — thinking on behalf of your opponent and neutralising threats before they form.", url:"blog.html#prophylaxis" },
  { tag:"Blog", title:"Mikhail Tal: The Magician from Riga", snippet:"A world champion who played chess as a dark art — sacrifices that defied calculation and refutation.", url:"blog.html#mikhail-tal" },
  { tag:"Blog", title:"Why You Should Study Grandmaster Games", snippet:"Puzzles build pattern recognition. But complete game study builds chess understanding.", url:"blog.html#study-grandmaster-games" },
  { tag:"Blog", title:"The Anatomy of a Breakthrough", snippet:"Every pawn chain has a base. Every base is a target. The art lies in identifying it first.", url:"blog.html#anatomy-breakthrough" },
];
